### ISSUE TITLE
Incorrect password and username

### ISSUE THREAD

**Issue by Ong-Yi-Kai** [FieteO/doccano_spacy#5]
Thanks for creating this repo! I think it will help me save alot of time and money for labelling on a project im working on!
However, I can't seem to authenticate using "admin:password" to the spacy-server.

To replicate:
1. fresh git clone repo
2. docker-compose up -d
3. curl -X POST -F 'foo=bar' -u 'admin:password' http://localhost:8080/auto_annotate

On the third step I get the response : {"detail":"Incorrect username or password"}

I noticed in the spacy-server docker container the environement variable is blank for SPACY_USER and SPACY_PASSWORD 
![image](https://user-images.githubusercontent.com/79684872/229951518-5575cdb2-88c6-48a0-abd8-ada49c34cbaa.png)

**Comment by FieteO** [comment]
Oh you are right @Ong-Yi-Kai ! I am not describing that in the README.
Generally speaking, you should be able to pass in those blanks and get a proper response:
```sh
$ curl -X POST -F 'foo=bar' -u ':' http://localhost:8080/auto_annotate
{"detail":[{"loc":["body"],"msg":"value is not a valid dict"
```
I have updated the instructions now to describe those missing pieces in regards to authorization. Specifically, you can [create an `.env` file](https://github.com/FieteO/doccano_spacy#spinning-up-the-server) to define credentials.
Let me know if there is still something unclear

**Comment by Ong-Yi-Kai** [comment]
Sorry for the late reply. But that really helped! thanks
